name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
   
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to 
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name:     XoClock.sln       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: XoClock/XoClock.csproj # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: SetVersion Number
      id: set_version
      shell: pwsh
      run: |
       $currentDate=Get-Date -Format "yyyy.MM.dd"
       $VersionNumber=$currentDate+"."+${{github.run_number}}   
       Write-Host("VersionNumber: "+$VersionNumber)      
       .\SetCsprojVersion.ps1 .\XoClock\XoClock.csproj $VersionNumber
#       Write-Host("::set-output name={VersionNumber}::{$VersionNumber}")
#       echo "::set-output name=VersionNumberr::{$VersionNumber}"
       
      - name: Check outputs
        shell: pwsh
        run: |
         echo ${{ steps.set_version.outputs.VersionNumberr }} 
         echo ${{ steps.set_version.outputs.VersionNumber }} 
        
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    - name: publish
      run: dotnet publish XoClock.sln -c Release --output ./bin
      
    - name: Create Zip Archive
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'XoClock.${{ steps.set_version.outputs.VersionNumber }}.zip'
        path: './bin'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
          draft: false
          prerelease: false
          tag_name: 2022.03.01.02
          release_name: XoClock_v2022
          body: New Automatic Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Upload zip on release url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: XoClock.win-x64.zip
        asset_name: XoClock.win-x64.zip
        asset_content_type: application/zip          